version: '3.9'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  api:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    command: npm start

  mongodb:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
